const fs = require('fs');
const path = require('path');

const IDEAS_DIR = 'ideas';
if (!fs.existsSync(IDEAS_DIR)) fs.mkdirSync(IDEAS_DIR, { recursive: true });

const markets = [
  'AI Tools', 'Local Services', 'Healthcare', 'Education', 'Finance',
  'Travel', 'Food Delivery', 'Home Services', 'Pet Care', 'Fitness',
  'Sustainability', 'Events', 'Freelancing', 'Senior Care', 'Childcare'
];

const tech = [
  'Mobile App', 'Web Platform', 'PWA', 'Chrome Extension', 'Telegram Bot',
  'AI Agent', 'SaaS Dashboard', 'Marketplace', 'Booking System', 'Tracker'
];

const monetization = [
  'Subscription', 'Commission', 'Freemium', 'Ads', 'Affiliate',
  'Featured Listings', 'API Access', 'White-label', 'Transaction Fees'
];

function generateIdea() {
  const market = markets[Math.floor(Math.random() * markets.length)];
  const technology = tech[Math.floor(Math.random() * tech.length)];
  const revenue = monetization[Math.floor(Math.random() * monetization.length)];
  
  const timestamp = Date.now();
  const filename = `idea-${timestamp}.md`;
  
  const idea = `# 💡 Business Idea: ${market} ${technology}

**Generated:** ${new Date().toISOString()}

## Concept
A ${technology.toLowerCase()} that solves problems in the ${market.toLowerCase()} space.

## Problem
- Pain point in ${market} industry
- Current solutions are outdated/expensive
- Market gap identified

## Solution
Build a ${technology.toLowerCase()} that:
- Streamlines ${market.toLowerCase()} workflows
- Reduces costs by 30-50%
- Improves user experience

## Tech Stack
- Frontend: React/Vue + Vite
- Backend: Node.js/Cloud Functions
- Database: Firebase/Supabase
- Hosting: GitHub Pages/Vercel

## Market Size
- Target: Malta + EU expansion
- TAM: €X million
- SAM: €X thousand

## Monetization
- Model: ${revenue}
- Price: €X/month or X% commission
- Projected MRR: €X,XXX by month 12

## MVP Features
1. Core functionality
2. User auth
3. Payment integration
4. Basic analytics

## Next Steps
- [ ] Validate with 10 potential customers
- [ ] Build landing page
- [ ] Create waitlist
- [ ] Develop MVP

---
*Auto-generated by ClawBot Idea Generator*
`;

  fs.writeFileSync(path.join(IDEAS_DIR, filename), idea);
  console.log(`✅ Generated: ${filename}`);
}

// Generate 3 ideas now
generateIdea();
generateIdea();
generateIdea();

console.log('\n🚀 Ideas saved to ideas/ folder');
